# Generated by Django 4.1.1 on 2022-09-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
