# Generated by Django 4.1.1 on 2022-09-19 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_management', '0002_nextofkin_patient_next_of_kin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='next_of_kin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient_management.nextofkin'),
        ),
    ]
