# Generated by Django 4.2.7 on 2023-11-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('insurance', 'Insurance')], default='cash', max_length=20),
        ),
    ]
