# Generated by Django 4.2.7 on 2023-12-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_vitalsigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_visit',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_visit',
            field=models.DateField(auto_now_add=True),
        ),
    ]
