# Generated by Django 4.2.7 on 2023-11-23 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_invoice_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.insurance'),
        ),
    ]
