# Generated by Django 4.2.7 on 2023-11-24 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_insurance_patient_patient_insurance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicine',
        ),
        migrations.AddField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.CreateModel(
            name='PrescribedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=50)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.prescription')),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.ManyToManyField(through='profiles.PrescribedMedicine', to='profiles.medicine'),
        ),
    ]
