# Generated by Django 4.2.7 on 2023-12-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_patient_last_visit_alter_patient_first_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
