# Generated by Django 4.2.7 on 2023-11-22 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextofkin',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.city'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.city'),
        ),
    ]
