# Generated by Django 4.2.7 on 2023-12-16 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_prescription_issue_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LabTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_date', models.DateField(auto_now_add=True)),
                ('results', models.TextField()),
                ('lab_test_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.labtestrequest')),
            ],
        ),
        migrations.RenameModel(
            old_name='Test',
            new_name='LabTest',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='requested_tests',
            field=models.ManyToManyField(to='profiles.labtest'),
        ),
    ]
