# Generated by Django 4.2.7 on 2023-12-17 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_labtestrequest_labtestresult_rename_test_labtest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsigns',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='labtestresult',
            name='lab_test_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.labtestrequest'),
        ),
    ]
