# Generated by Django 4.2.7 on 2023-11-22 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_nextofkin_city_alter_patient_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rooms', models.IntegerField()),
                ('beds_per_room', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='emergencyroom',
            name='name',
        ),
        migrations.AddField(
            model_name='emergencyroom',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.ward'),
        ),
    ]
