# Generated by Django 4.2.7 on 2023-11-22 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_ward_remove_emergencyroom_name_emergencyroom_ward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_number',
        ),
        migrations.AddField(
            model_name='room',
            name='number',
            field=models.CharField(default='00', max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('AP', 'Appointment'), ('PA', 'Patient')], default='PA', max_length=2),
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.room')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ward')),
            ],
        ),
    ]
