# Generated by Django 4.2.7 on 2023-11-22 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_admission_ward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='bed_number',
        ),
        migrations.AddField(
            model_name='admission',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.room'),
        ),
    ]
